### ISSUE TITLE
Agree on launch set of apps and tweak them

### ISSUE THREAD

**Issue by rufuspollock** [Scifabric/crowdcrafting.org#10]
- Apps need tweaking to be a bit more responsive ...
  - Need feedback as to what is happening

Launch set of apps (listed on front page too!):
- Flickr Person
- Urban parks
- Melanoma
- Create your own ...

**Comment by teleyinex** [comment]
Flickr Person, Urban Parks and Melanoma now feature a new thumbnail.

I've updated Urban Parks to use the same toolbar that I'm using in ForestWatchers, so now is more beautiful and user friendly :-)

I'll work in listing the apps in the front page of pybossa. I guess this could be done like picking 3 random apps from pybossa registered apps, so the front page will look a bit more dynamic every time you log in. What do you think?

**Comment by teleyinex** [comment]
@PyBossa The front page now features two random applications :-) and invites users to create their own. Please check it out, and let me know what you think about it.

**Comment by teleyinex** [comment]
@PyBossa All the apps have been improved, however they are not perfect :) Let me know which changes do you want in each so I can fix them.
