### ISSUE TITLE
Move to Heroku / Geneva servers

### ISSUE THREAD

**Issue by rufuspollock** [Scifabric/crowdcrafting.org#13]
Either way let's move off s063.okserver.org ...

@teleyinex what's your ETA for the Geneva servers?

**Comment by teleyinex** [comment]
Hi @rgrp 

I've been talking with the people of the Geneva servers, and we need a bit more of time. Currently we have memory issues, as the forestwatchers.net server is full with PyBossa + Mapserver + PostgreSQL + MySQL. I'll keep you updated, but there is no ETA for the moment. We have a second server at CERN, so I'll check if this is possible. I'll let you know it.

**Comment by teleyinex** [comment]
Fully operational in Geneva servers right now.
