### ISSUE TITLE
List other projects in fron page using PyBossa

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/crowdcrafting.org#16]

**Comment by rufuspollock** [comment]
BTW: as a tip on implementation: I think you can add functions that can be used inside jinja template. We coudl start centralizing these in a "webhelpers" file and a function like this would be perfect.

**Comment by teleyinex** [comment]
Yes! I'm using those helpers already in PyBossa but in each template. As you said: we need to move them to a specific file. :+1:

**Comment by teleyinex** [comment]
Done! [Check this commit](https://github.com/PyBossa/pybossa/commit/8e63c5ca88055f5cbb897fdb9970e3c4a68b949a)
