### ISSUE TITLE
user can't easily access featured apps

### ISSUE THREAD

**Issue by LaurieJ** [Scifabric/crowdcrafting.org#19]
On http://crowdcrafting.org/app/ the text at the top says  "The applications can be sorted in three categories:" but only "Published" is shown and there's no way to sort or filter to see Featured apps, other than by reading through the whole list and spotting them. 

As a new user looking for interesting apps to try, I want to be able to find the Featured content easily.

![Screen Shot 2013-02-04 at 11 33 41](https://f.cloud.github.com/assets/457927/123401/411ee706-6ebf-11e2-9db8-2716201ed13e.png)

**Comment by teleyinex** [comment]
Hi,

Thanks a lot for this opening this issue. I've opened in parallel an issue regarding the whole UX and UI of the site, so I'm going to close this one. Please, check [this](https://github.com/PyBossa/pybossa/issues/356) and [this issue](https://github.com/PyBossa/pybossa/issues/357) regarding the overall UX and UI problems of PyBossa.

Cheers,

Daniel
