### ISSUE TITLE
Submit button not obvious enough to avoid on mobile

### ISSUE THREAD

**Issue by mmnoo** [Scifabric/crowdcrafting.org#26]
On mobile it is really easy to accidentally hit submit, which I did with a half filled out form (jurisdiction and half of name field was filled in.) The fields weren't blank, just wrong values.

I hit the back button and filled out the form for the same document and hit submit again. I doubt it really submitted because there was no success message like the first time, but there was also no error message either. 

Suggestions:
- Add confirm submit screen/pop up
- Make submit button look like a button or interactive in some way so that one knows to avoid it if they haven't fully looked at it yet. 

Thanks :)

**Comment by teleyinex** [comment]
Dear Melissa,

You are right! We've this small issue, and we'll fix it. We're currently improving the whole usability of different projects in phones, and we'll make sure that your comments are taking into account.

Cheers,

Daniel

PS: By the way, the system didn't allow you to save the same answer twice. We do this to ensure quality.

**Comment by alejandrodob** [comment]
I've improved the visibility of the submit button. Please check that it work on your devices (I've tried on a real iOS device and several Android-emulated devices too)

**Comment by mmnoo** [comment]
Liking the use of red!

The button isnt working on my desktop FF...

**Comment by alejandrodob** [comment]
Sorry about that. It should now be fixed.
