### ISSUE TITLE
Crowdcrafting Task Presenter record no data

### ISSUE THREAD

**Issue by ngonthier** [Scifabric/crowdcrafting.org#34]
Hi,

I am pretty lost with Crowdcrafting. I am trying to write a Task Presenter that ask 6 questions for each images of the database and the databas is provided by Dropbox. 
I don't really know where to ask my question. When I answer the question there are no information recorded in the Exports tasks.

You can find here my task presenter code, do you know where is the problem ?

[crowsourding.txt](https://github.com/Scifabric/crowdcrafting.org/files/1643305/crowsourding.txt)

**Comment by teleyinex** [comment]
Hi,

If you only need to ask 6 questions, we would suggest you to use the Wizard. The wizard kicks in as soon as you create a project. Did you try that? 

Check this video tutorial: https://www.youtube.com/watch?v=bjynbjfiCEc

Cheers
