### ISSUE TITLE
PyBossa announcement post

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/crowdcrafting.org#6]
- Draft available here: http://science.okfnpad.org/pybossa-posts
- Aim to publish it this Thursday 07/JUN/2012

**Comment by rufuspollock** [comment]
cf https://github.com/PyBossa/pybossa/issues/30. Obviously post covers software and service.

**Comment by teleyinex** [comment]
@rgrp I think that we are ready to publish it. The only missed items are the screenshots and screencasts.

**Comment by rufuspollock** [comment]
FIXED.
